### ISSUE TITLE
部署安全优化建议

### ISSUE THREAD

**Issue by internelp** [star7th/showdoc#2260]
文档地址：https://www.showdoc.com.cn/help/65610

我在使用 docker 部署时，发现文档中使用的权限非常大，有一定的安全隐患，以下是修改建议。

1、新建存放showdoc数据的目录授权时不要使用777

```bash
mkdir -p /showdoc_data/html
chmod  -R 750 /showdoc_data
```

2、启动docker无需使用root权限

去掉 `--user=root  --privileged=true `

```bash
docker run -d --name showdoc --restart=always -p 4999:80 \
-v /showdoc_data/html:/var/www/html/ star7th/showdoc
```

另外建议在 docker 镜像中也使用普通用户。

3、使用随机的默认密码

文档中：`账户密码是showdoc/123456`
建议：密码在初始化时生成随机密码，仅显示一次。或在初始化时要求用户设置密码。

附 docker-compose.yaml 

```yaml
version: '3.8'
services:
  showdoc:
    image: star7th/showdoc
    container_name: showdoc
      #user: root
    restart: always
      #privileged: true
    ports:
      - "4999:80"
    volumes:
      - /opt/showdoc/html:/var/www/html
```
