### ISSUE TITLE
安卓和苹果的APP都不能访问私服

### ISSUE THREAD

**Issue by zuohuijun** [star7th/showdoc#780]
在笔记本上ubuntu 19.10部署showdoc。

Docker是用docker .io安装的，版本19.03。

使用最新的showdoc镜像，用docker compose启动。

现在的问题是在笔记本上访问192.168.3.XXX:4999正常，

但手机端APP设置私服地址后，经过验证提示：**该网址无法正常连接。**

```yaml
version: "3.7"

services:
  wiznote:
    image: star7th/showdoc
    container_name: showdoc
    ports:
      - "4999:80"
      - "4443:443"
    restart: always
    volumes:
      - /root/showdocdata:/var/www/html/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
```

利用docker logs查看日志如下：

2020/03/03 21:35:16 [notice] 17#17: OS: Linux 5.3.0-40-generic
2020/03/03 21:35:16 [notice] 17#17: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2020/03/03 21:35:16 [notice] 17#17: start worker processes
2020/03/03 21:35:16 [notice] 17#17: start worker process 18
2020/03/03 21:35:16 [notice] 17#17: start worker process 19
2020/03/03 21:35:16 [notice] 17#17: start worker process 20
2020/03/03 21:35:16 [notice] 17#17: start worker process 21
2020-03-03 21:35:17,953 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-03-03 21:35:17,954 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
