### ISSUE TITLE
支持在k8s里面部署showdoc吗?

### ISSUE THREAD

**Issue by xiahuhu1** [star7th/showdoc#838]
showdoc 支持在k8s里面部署嘛？我这边部署完了之后出现各种bug：
1、安装提示“本程序已经安装过！如果要解除安装锁定，则可删除install目录下的install.lock文件后再重新访问本页面”，显示重复安装。
2、登录session会话失效，老是提示“用户未登录，请登录”
3、出现页面闪退

后来换成docker部署上面的问题没有出现，可能是我k8s部署的有问题，能出一个k8s部署的教程吗？

**Comment by star7th** [comment]
k8s 不少管理容易的吗，容器安装没问题它怎么会有问题。

xiahuhu1 <notifications@github.com> 于2020年4月9日周四 下午3:38写道：

**Comment by star7th** [comment]
k8s 不是管理容器的吗，容器安装没问题它怎么会有问题。

Chen Xing <xing7th@gmail.com> 于2020年4月9日周四 下午3:40写道：

**Comment by star7th** [comment]
这是纯k8s的使用问题，跟showdoc没什么关系。怎么用k8s使用容器的问题。

Chen Xing <xing7th@gmail.com> 于2020年4月9日周四 下午3:40写道：

**Comment by xiahuhu1** [comment]
可以确定不是镜像文件的问题，问题应该是出在k8s上面，通过这个yaml文件部署的，不确定是哪个地方出了问题。部署之后容器运行的都是正常的。
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: showdoc
  name: showdoc
  namespace: yunwei
spec:
  replicas: 2
  selector:
    matchLabels:
      app: showdoc
  template:
    metadata:
      labels:
        app: showdoc
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/star7th/showdoc:latest
        name: showdoc
        resources:
          requests:
            cpu: 0.5
            memory: 500Mi
          limits:
            cpu: 0.5
            memory: 500Mi
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - name: showdoc-data
          mountPath: /var/www/html
      volumes:
      - name: showdoc-data
        hostPath:
          path: /ccdata/k8s/data/showdoc

---
apiVersion: v1
kind: Service
metadata:
  name: showdoc
  namespace: yunwei
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: showdoc
  type: NodePort
```
