### ISSUE TITLE
写了一个docker compose 分享下

### ISSUE THREAD

**Issue by gpqhl0071** [star7th/showdoc#898]
写了一个docker compose 分享下：

```
version: '3.1'
services:
    showdoc:
        restart: always
        image: star7th/showdoc
        container_name: showdoc_compose
        ports:
            - 4999:80
        environment:
            user: root
        privileged: true
        volumes:
            - /Users/penggao/soft/showdoc/showdoc_data/html:/var/www/html/
```
